spring:
  application:
    name: shortener

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 86400000 # 24 hours
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "shortener:"

  # PostgreSQL database connection configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bitly_clone}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  # Hibernate (JPA) configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Application server port configuration (default: 8080)
server:
  port: ${PORT:8080}

app:
  domain: ${APP_DOMAIN:http://localhost:8080/}
  jwt:
    # Secret Key
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    # 1 hour = 3600000 ms (Access Token)
    expiration: ${JWT_EXPIRATION:3600000}
    # 7 days = 604800000 ms (Refresh Token)
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

springdoc:
  swagger-ui:
    persist-authorization: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestId:-SYSTEM}] %-5level %logger{36} - %msg%n"
  level:
    com.thinh.shortener: DEBUG
    org.springframework.web: INFO
