spring:
  application:
    name: shortener

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 86400000 # 24 hours
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "shortener:"

  # PostgreSQL database connection configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/bitly_clone
    username: postgres
    # To avoid exposing the password directly: # If the DB_PASSWORD environment variable exists, it will be used. # Otherwise, it defaults to '123456' (the value after the colon).
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  # Hibernate (JPA) configuration
  jpa:
    hibernate:
      # 'update' automatically updates the database schema when the Entity changes
      ddl-auto: update
    show-sql: true # Print SQL statements to the console for easier debugging
    properties:
      hibernate:
        format_sql: true # Format SQL statements for better readability
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Application server port configuration (default: 8080)
server:
  port: 8080

app:
  jwt:
    # Secret Key
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    # 1 hour = 3600000 ms (Access Token)
    expiration: 3600000
    # 7 days = 604800000 ms (Refresh Token)
    refresh-expiration: 604800000

springdoc:
  swagger-ui:
    persist-authorization: true